version: 1
jobs:
  build:
    working_directory: ~/ipo-proj
    docker:
      - image: cimg/python:3.9.6
        environment:
          PIPENV_VENV_IN_PROJECT: 'true'
    steps:
      - checkout
      - run:
          command: |
            python3 -m pip install pipenv
            alias python3=python3.9
            sudo apt update
            sudo apt install redis-server
            python3 -m pip install bs4
            python3 -m pip install redis
            python3 -m pip install numpy
            python3 -m pip install schedule
            python3 -m pip install celery
            python3 -m pip install pyTelegramBotAPI
            python3 -m pip install requests
      - run:
          name: Fetch details
          command: python3 main.py fetch_and_store
      - run:
          name: Start server
          command: python3 main.py fetch_ipo_details