version: 2
jobs:
  build:
    working_directory: ~/ipo-proj
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run:
          command: |
            python3 -m pip install pipenv
            sudo apt update
            sudo add-apt-repository universe
            sudo apt install redis-server
            alias python3=python3.9
            python3 -m pip install bs4
            python3 -m pip install redis
            python3 -m pip install numpy
            python3 -m pip install schedule
            python3 -m pip install celery
            python3 -m pip install pyTelegramBotAPI
            python3 -m pip install requests
      - run:
          name: Fetch old info
          command: python3 main.py fetch_and_store
      - run:
          name: Fetch details
          command: python3 main.py fetch_v2
      - run:
          name: Start server
          command: python3 main.py fetch_ipo_details
      - persist_to_workspace:
          root: .
          paths:
            - .
