version: 1
jobs:
  build:
    working_directory: ~/ipo-proj
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            pip install --upgrade setuptools
            pip install --upgrade pip
            python3 -m pip install pipenv
            alias python3=python3.9
            sudo apt update
            sudo add-apt-repository universe
            sudo apt install redis-server
            sudo python3 -m pip install awsebcli --upgrade
            python3 -m pip install bs4
            python3 -m pip install redis
            python3 -m pip install numpy
            python3 -m pip install schedule
            python3 -m pip install celery
            python3 -m pip install pyTelegramBotAPI
            python3 -m pip install requests
      - run:
          name: Fetch details
          command: python3 main.py fetch_and_store
      - run:
          name: Start server
          command: python3 main.py fetch_ipo_details
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./app/build s3://ipo-bot

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build